name: Terraform Deploy (LocalStack)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
        options: >-
          --health-cmd "curl -s http://localhost:4566/_localstack/health | grep '\"s3\": \"running\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform init -backend=false

      - name: Plan de Terraform
        run: terraform plan -out=tfplan

      - name: Aplicar cambios (Auto-Approve)
        run: terraform apply -auto-approve tfplan
